version: 2
jobs:
  test:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
  publish:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn build
      - run: yarn publish
workflows:
  version: 2
  test_builds:
    jobs:
      - test
  tagged_builds:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
